//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistenciaUsuario
    {
        public int id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> hora_ingreso { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
        public Nullable<int> id_estado_asistencia { get; set; }
        public string comentario { get; set; }
    
        public virtual EstadosAsistencia EstadosAsistencia { get; set; }
    }
}
