//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiclosPruebaDetalle
    {
        public int id_ciclo_prueba_detalle { get; set; }
        public Nullable<int> id_ciclo_prueba { get; set; }
        public Nullable<int> id_caso_prueba { get; set; }
        public Nullable<int> id_usuario_tester { get; set; }
        public Nullable<decimal> cantidad_horas { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<bool> aceptado { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        public virtual CasosDePrueba CasosDePrueba { get; set; }
        public virtual CiclosPrueba CiclosPrueba { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
