//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiclosPrueba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CiclosPrueba()
        {
            this.CiclosPruebaDetalles = new HashSet<CiclosPruebaDetalle>();
            this.FacturasDetalles = new HashSet<FacturasDetalle>();
        }
    
        public int id_ciclo_prueba { get; set; }
        public Nullable<System.DateTime> fecha_inicio_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_fin_ejecucion { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public Nullable<int> id_plan_prueba { get; set; }
        public Nullable<bool> aceptado { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        public virtual PlanesDePrueba PlanesDePrueba { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiclosPruebaDetalle> CiclosPruebaDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasDetalle> FacturasDetalles { get; set; }
    }
}
