//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int id_formulario { get; set; }
        public int id_perfil { get; set; }
        public Nullable<int> borrado { get; set; }
    
        public virtual Formulario Formulario { get; set; }
        public virtual Perfile Perfile { get; set; }
    }
}
