//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SueldoDescuento
    {
        public int id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_descuento { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual Descuento Descuento { get; set; }
        public virtual Sueldo Sueldo { get; set; }
    }
}
